article_module/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.ArticlesView.as_view(), name='articles_list'),
    path('cat/<str:category>', views.ArticlesView.as_view(), name='articles_by_category_list'),
    path('<pk>/', views.ArticleDetailView.as_view(), name='articles_detail'),
    path('add-article-comment', views.AddArticleComment, name='add_article_comment'),
]

home_module/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.HomeView.as_view(), name='home_page'),
    path('about-us', views.AboutView.as_view(), name='About-us'),
]

obsidian_shop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('home_module.urls')),
    path('order/', include('order_module.urls')),
    path('account/', include('account_module.urls')),
    path('products/', include('product_module.urls')),
    path('articles/', include('article_module.urls')),
    path('contact-us/', include('contact_module.urls')),
    path('user/', include('user_module.urls')),
    path('admin/', admin.site.urls, name="admin")

]

urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

article_module/models.py
from django.db import models
# Create your models here.
from jalali_date import date2jalali

from account_module.models import User


class ArticleCategory(models.Model):
    parent = models.ForeignKey('ArticleCategory', null=True, on_delete=models.CASCADE, verbose_name='دسته بندی والد')
    title = models.CharField(max_length=200, verbose_name='عنوان دسته بندی')
    url_title = models.CharField(max_length=200, verbose_name='عنوان در url', unique=True)
    is_active = models.BooleanField(default=True, verbose_name='فعال / غیر فعال')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'دسته بندی مقاله'
        verbose_name_plural = 'دسته بندی های مقاله'


class Article(models.Model):
    title = models.CharField(max_length=300, verbose_name='عنوان مقاله')
    slug = models.SlugField(max_length=400, db_index=True, allow_unicode=True, verbose_name='عنوان در url')
    image = models.ImageField(upload_to='images/articles', verbose_name='تصویر مقاله')
    short_description = models.TextField(verbose_name='توضیحات کوتاه')
    text = models.TextField(verbose_name='متن مقاله')
    is_active = models.BooleanField(default=True, verbose_name='فعال / غیر فعال')
    selected_category = models.ManyToManyField(ArticleCategory, verbose_name='دسته بندی ها')
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='نویسنده', null=True, editable=False)
    create_date = models.DateTimeField(auto_now_add=True, editable=False, verbose_name='تاریخ ثبت')

    def __str__(self):
        return self.title

    def get_shamsi_create_date(self):
        return date2jalali(self.create_date)

    def get_shamsi_create_time(self):
        return self.create_date.strftime('%H:%M')

    class Meta:
        verbose_name = 'مقاله'
        verbose_name_plural = 'مقالات'


class ArticleComment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE, verbose_name='مقاله')
    parent = models.ForeignKey('ArticleComment', null=True, blank=True, on_delete=models.CASCADE, verbose_name='والد')
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='کاربر')
    create_date = models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')
    text = models.TextField(verbose_name='متن نظر')

    def __str__(self):
        return self.user.get_full_name()

    class Meta:
        verbose_name = 'نظر'
        verbose_name_plural = 'نظرات'

article_module/views.py
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render
from django.views.generic import ListView, DetailView

from . import models
# Create your views here.
from .models import ArticleCategory, Article, ArticleComment


# Class Base Views

class ArticlesView(ListView):
    template_name = 'article_module/article_page.html'
    model = models.Article
    paginate_by = 10

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ArticlesView, self).get_context_data()
        return context

    def get_queryset(self):
        query = super(ArticlesView, self).get_queryset()
        query = query.filter(is_active=True)
        category_name = self.kwargs.get('category')

        if category_name is not None:
            query = query.filter(selected_category__url_title__iexact=category_name)

        return query


class ArticleDetailView(DetailView):
    model = Article
    template_name = 'article_module/article_detile_page.html'

    def get_queryset(self):
        query = super(ArticleDetailView, self).get_queryset()
        query.filter(is_active=True)
        return query

    def get_context_data(self, **kwargs):
        context = super(ArticleDetailView, self).get_context_data()
        article = kwargs.get('object')
        context['comments'] = ArticleComment.objects.filter(article_id=article.id, parent=None).order_by(
            '-create_date').prefetch_related(
            'articlecomment_set')
        context['comments_count'] = ArticleComment.objects.filter(article_id=article.id, parent=None).count()
        return context


# Function Base Views


def article_categories_partial(request: HttpRequest):
    article_main_categorys = ArticleCategory.objects.prefetch_related('articlecategory_set').filter(is_active=True, parent_id=None)
    context = {
        'main_categorys': article_main_categorys
    }
    return render(request, 'article_module/partiaals/article_category_partial.html', context)


def AddArticleComment(request: HttpRequest):

    if request.user.is_authenticated:
        article_id = request.GET.get('articleid')
        article_comment = request.GET.get('comment')
        parent_id = request.GET.get('parentid')
        print(article_id, article_comment, parent_id)
        new_commant = ArticleComment(article_id=article_id, text=article_comment, user_id=request.user.id,
                                     parent_id=parent_id)
        new_commant.save()
        return render(request, 'article_module/includes/articlrd_comment_partial.html', {
            'comments': ArticleComment.objects.filter(article_id=article_id, parent=None).order_by(
                '-create_date').prefetch_related('articlecomment_set'),
            'comments_count': ArticleComment.objects.filter(article_id=article_id).count()
        })
    return HttpResponse("hellow")

article_module/templates/article_module/article_detile_page.html
{% extends 'shared/_layout.html' %}
{% load render_partial %}
{% load poll_extras %}
{% load thumbnail %}

{% block title %}
    جزییات مقاله
{% endblock %}

{% block content %}

    <section>
        <div class="container">
            <div class="row">

                <div class="col-sm-9">
                    <div class="blog-post-area">
                        <h2 class="title text-center">{{ article.title }}</h2>
                        <div class="single-blog-post">
                            <h3>{{ article.title }}</h3>
                            <div class="post-meta">
                                <ul>
                                    {% if article.author %}
                                        <li><i class="fa fa-user"></i>{{ article.author }}</li>
                                    {% endif %}
                                    <li><i class="fa fa-clock-o"></i>{{ article.create_date | shamsi_time }}</li>
                                    <li><i class="fa fa-calendar"></i>{{ article.create_date | shamsi_date }}</li>
                                </ul>
                                <span>
										<i class="fa fa-star"></i>
										<i class="fa fa-star"></i>
										<i class="fa fa-star"></i>
										<i class="fa fa-star"></i>
										<i class="fa fa-star-half-o"></i>
								</span>
                            </div>
                            <a href="">
                                {% thumbnail article.image "862x398" crop='center' as im %}
                                    <img src="{{ im.url }}">
                                {% endthumbnail %}
                            </a>
                            <p>
                                {{ article.short_description }}
                                {{ article.text }}
                            </p>
                            <div class="pager-area">
                                <ul class="pager pull-left">
                                    <li><a href="#">قبلی</a></li>
                                    <li><a href="#">بعـدی</a></li>
                                </ul>
                            </div>
                        </div>
                    </div><!--/blog-post-area-->

                    <div class="rating-area">
                        <ul class="ratings">
                            <li class="rate-this">به این مطلب امتیـاز دهیـد :</li>
                            <li>
                                <i class="fa fa-star color"></i>
                                <i class="fa fa-star color"></i>
                                <i class="fa fa-star color"></i>
                                <i class="fa fa-star"></i>
                                <i class="fa fa-star"></i>
                            </li>
                            <li class="color">( 6 نظـر )</li>
                        </ul>
                        <ul class="tag">
                            <li>برچسب :</li>
                            <li><a class="color" href="">برچسب 1 <span>/</span></a></li>
                            <li><a class="color" href="">برچسب 2 <span>/</span></a></li>
                            <li><a class="color" href="">برچسب 3</a></li>
                        </ul>
                    </div><!--/rating-area-->

                    <div class="socials-share">
                        <a href=""><img src="/static/images/blog/socials.png" alt=""></a>
                    </div><!--/socials-share-->

                    {% if article.author %}
                        <div class="media commnets">
                            <a class="pull-right" href="#">
                                {% if article.author.avatar %}
                                    {% thumbnail article.author.avatar "121x86" crop='center' as im %}
                                        <img class="media-object" src="{{ im.url }}" alt="">
                                    {% endthumbnail %}
                                {% else %}
                                    {% thumbnail article.image "121x86" crop='center' as im %}
                                        <img class="media-object" src="{{ im.url }}" alt="">
                                    {% endthumbnail %}
                                {% endif %}


                            </a>
                            <div class="media-body">
                                <h4 class="media-heading">{{ article.author }}</h4>
                                <p>{{ article.author.about_us }}</p>
                                <div class="blog-socials">
                                    <ul>
                                        <li><a href=""><i class="fa fa-facebook"></i></a></li>
                                        <li><a href=""><i class="fa fa-twitter"></i></a></li>
                                        <li><a href=""><i class="fa fa-dribbble"></i></a></li>
                                        <li><a href=""><i class="fa fa-google-plus"></i></a></li>
                                    </ul>
                                    <a class="btn btn-primary" href="">سایـر مطالب نویسنده</a>
                                </div>
                            </div>
                        </div><!--Comments-->

                    {% endif %}

                    <div class="response-area" id="comments_area">
                        <h2>نظرات ({{ comments_count }})</h2>
                        <ul class="media-list">
                            {% for comment in comments %}
                                <li class="media" id="command_{{ comment.id }}">
                                    <a class="pull-right" href="#">
                                        <img class="media-object" src="/static/images/blog/Customer.jpg" alt="">
                                    </a>
                                    <div class="media-body">
                                        <ul class="sinlge-post-meta">
                                            <li><i class="fa fa-user"></i>{{ comment.user }}</li>
                                            <li><i class="fa fa-clock-o"></i>{{ comment.create_date | shamsi_time }}
                                            </li>
                                            <li><i class="fa fa-calendar"></i>{{ comment.create_date | shamsi_date }}
                                            </li>
                                        </ul>
                                        <p>{{ comment.text }}</p>
                                        <a class="btn btn-primary" onclick="FillParentId( {{ comment.id }} )"><i class="fa fa-reply"></i>پاسـخ</a>
                                    </div>
                                </li>
                                {% for sub_comment in comment.articlecomment_set.all %}
                                    <li class="media second-media" id="command_{{ comment.id }}">
                                        <a class="pull-right" href="#">
                                            <img class="media-object" src="/static/images/blog/Customer.jpg" alt="">
                                        </a>
                                        <div class="media-body">
                                            <ul class="sinlge-post-meta">
                                                <li><i class="fa fa-user"></i>{{ sub_comment.user }}</li>
                                                <li>
                                                    <i class="fa fa-clock-o"></i>{{ sub_comment.create_date | shamsi_time }}
                                                </li>
                                                <li>
                                                    <i class="fa fa-calendar"></i>{{ sub_comment.create_date | shamsi_date }}
                                                </li>
                                            </ul>
                                            <p>{{ comment.text }}</p>

                                        </div>
                                    </li>
                                {% endfor %}
                            {% endfor %}


                        </ul>
                    </div><!--/Response-area-->
                    <div class="replay-box" id="command_form">
                        {% if request.user.is_authenticated %}
                            <div class="row">

                            <div class="col-sm-12">
                                <h2>نظـر خود را بنویسیـد</h2>
                                <div class="text-area" >
                                    <input type="hidden" id="parent_id" value="">
                                    <div class="blank-arrow">
                                        <label>متن پیام</label>
                                    </div>
                                    <span>*</span>
                                    <textarea name="message" rows="11" id="CommentText"></textarea>
                                    <a class="btn btn-primary" onclick="sendComment({{ article.id }})">ارسـال نظـر</a>
                                </div>
                            </div>

                        </div>
                            {% else %}
                            <div class="alert alert-warning">
                                برای درج نظر ابتدا لاگین کنید
                            </div>
                        {% endif %}

                    </div><!--/Repaly Box-->
                </div>

                <div class="col-sm-3">
                    <div class="left-sidebar">
                        <h2>دسته بندی محصولات</h2>
                        <div class="panel-group category-products" id="accordian"><!--category-productsr-->
                            <div class="panel panel-default">
                                <div class="panel-heading">
                                    <h4 class="panel-title">
                                        <a data-toggle="collapse" data-parent="#accordian" href="#sportswear">
                                            <span class="badge pull-right"><i class="fa fa-plus"></i></span>
                                            دسته 1
                                        </a>
                                    </h4>
                                </div>
                                <div id="sportswear" class="panel-collapse collapse">
                                    <div class="panel-body">
                                        <ul>
                                            <li><a href="">محصول 1 </a></li>
                                            <li><a href="">محصول 2 </a></li>
                                            <li><a href="">محصول 3 </a></li>
                                            <li><a href="">محصول 4</a></li>
                                            <li><a href="">محصول 5</a></li>
                                        </ul>
                                    </div>
                                </div>
                            </div>

                            {% render_partial 'article_module.views.article_categories_partial' %}

                            <div class="brands_products"><!--brands_products-->
                                <h2>برنـد ها</h2>
                                <div class="brands-name">
                                    <ul class="nav nav-pills nav-stacked">
                                        <li><a href=""> <span class="pull-left">(50)</span>برنـد 1</a></li>
                                        <li><a href=""> <span class="pull-left">(56)</span>برنـد 2</a></li>
                                        <li><a href=""> <span class="pull-left">(27)</span>برنـد 3</a></li>
                                        <li><a href=""> <span class="pull-left">(32)</span>برنـد 4</a></li>
                                        <li><a href=""> <span class="pull-left">(5)</span>برنـد 5</a></li>
                                    </ul>
                                </div>
                            </div><!--/brands_products-->

                            <div class="shipping text-center"><!--shipping-->
                                <img src="/static/images/home/shipping.jpg" alt=""/>
                            </div><!--/shipping-->

                        </div>
                    </div>

                </div>
            </div>
    </section>

{% endblock %}

article_module/templates/article_module/article_page.html
{% extends 'shared/_layout.html' %}
{% load thumbnail %}
{% load poll_extras %}
{% load render_partial %}

{% block title %}

    لیست مقالات

{% endblock %}

{% block content %}

    <section>
        <div class="container">
            <div class="row">

                <div class="col-sm-9">
                    <div class="blog-post-area">
                        <h2 class="title text-center">آخریـن اخبـار</h2>

{#                        {{ date }}#}

                        {% for article in article_list %}
                            {% if article.is_active %}
                                <div class="single-blog-post">
                            <h3>{{ article.title }}</h3>
                            <div class="post-meta">
                                <ul>
                                    {% if article.author %}
                                        <li><i class="fa fa-user"></i>{{ article.author }}</li>
                                    {% endif %}
                                    <li><i class="fa fa-clock-o"></i>{{ article.create_date | shamsi_time }}</li>
                                    <li><i class="fa fa-calendar"></i>{{ article.create_date | shamsi_date}}</li>
                                </ul>
                                <span>
										<i class="fa fa-star"></i>
										<i class="fa fa-star"></i>
										<i class="fa fa-star"></i>
										<i class="fa fa-star"></i>
										<i class="fa fa-star-half-o"></i>
								</span>
                            </div>
                            <a href="">
                                {% thumbnail article.image "862x398" crop='center' as im %}
                                    <img src="{{ im.url }}">
                                {% endthumbnail %}
{#                                <img src="{{ article.image.url }}" alt="">#}
                            </a>
                            <p>{{ article.short_description }}</p>
                            <a class="btn btn-primary" href="{% url 'articles_detail' pk=article.pk %}">ادامـه مطلب</a>
                        </div>
                            {% endif %}
                        {% endfor %}

{#                        <div class="pagination-area">#}
                            <ul class="pagination">
                            {#							<li class="active"><a href="">1</a></li>#}
                            {#							<li><a href="">2</a></li>#}
                            {#							<li><a href="">3</a></li>#}
                            {#							<li><a href="">»</a></li>#}
                            {% if page_obj.has_previous %}
                                <li><a href="?page= {{ page_obj.previous_page_number }}">قبلی</a></li>
                            {% endif %}
                            {% for foo in paginator.page_range %}
                                <li {% if page_obj.number == foo %} class="active" {% endif %} ><a
                                        href="?page={{ foo }} ">{{ foo }}</a></li>
                            {% endfor %}
                            {% if page_obj.has_next %}
                                <li><a href="?page= {{ page_obj.next_page_number }}">بعدی</a></li>
                            {% endif %}

                        </ul>
{#                        </div>#}
                    </div>
                </div>

                <div class="col-sm-3">
                    <div class="left-sidebar">

                        {% render_partial 'article_module.views.article_categories_partial' %}

                        <div class="brands_products"><!--brands_products-->
                            <h2>برنـد ها</h2>
                            <div class="brands-name">
                                <ul class="nav nav-pills nav-stacked">
                                    <li><a href=""> <span class="pull-left">(50)</span>برنـد 1</a></li>
                                    <li><a href=""> <span class="pull-left">(56)</span>برنـد 2</a></li>
                                    <li><a href=""> <span class="pull-left">(27)</span>برنـد 3</a></li>
                                    <li><a href=""> <span class="pull-left">(32)</span>برنـد 4</a></li>
                                    <li><a href=""> <span class="pull-left">(5)</span>برنـد 5</a></li>
                                </ul>
                            </div>
                        </div><!--/brands_products-->

                        <div class="price-range"><!--price-range-->
                            <h2>فیلتـر قیمـت</h2>
                            <div class="well">
                                <input type="text" class="span2" value="" data-slider-min="0" data-slider-max="1000000"
                                       data-slider-step="5" data-slider-value="[250,450]" id="sl2"><br/>
                                <b>1.000.000 ريال</b> <b class="pull-left">0 ريال</b>
                            </div>
                        </div><!--/price-range-->

                        <div class="shipping text-center"><!--shipping-->
                            <img src="/static/images/home/shipping.jpg" alt=""/>
                        </div><!--/shipping-->

                    </div>
                </div>

            </div>
        </div>
    </section>

{% endblock %}